### ISSUE TITLE
GitHub Latest - latest issues button gone

### ISSUE THREAD

**Issue by JourneyOver** [Ede123/userscripts#16]
So seems like github has forced the newest layout on people (or at least myself) with no way to revert it due to the feature preview no longer listing it, in the process of doing so it has now broken the github latest userscript, as the latest issues button is now missing.

Checking chrome console the userscript seems to be throwing the following error message:

![OEsoyrd](https://user-images.githubusercontent.com/13910285/85467759-3991a680-b571-11ea-9eb6-3b2fee2499ff.png)

**Comment by jerone** [comment]
Yes please, I don't have time to suggest a fix.
