### ISSUE TITLE
github latest has stopped working.

### ISSUE THREAD

**Issue by JourneyOver** [Ede123/userscripts#17]
Not sure if you even check this repository anymore or anything, but the "github latest" script has stopped working today due to GitHub changing the layout of the navbar, now it's no longer a list but instead a simple collection of anchor elements.

**Comment by JourneyOver** [comment]
Seems to be an actual easy fix.

Change:

```js
    var reponav_list = document.querySelector("nav.js-repo-nav > ul");
    if (reponav_list) {
        var list_item_issues_copy = reponav_list.children[1].cloneNode(true);
        list_item_issues_copy.style.marginLeft = "auto";

        var button = list_item_issues_copy.firstElementChild;
        button.id = "latest-button"
        button.href += "?sort=updated";
        button.style.float = "right";
```

to

```js
    var reponav_list = document.querySelector("nav.js-repo-nav > .UnderlineNav-body");
    if (reponav_list) {
        var list_item_issues_copy = reponav_list.children[1].cloneNode(true);
        list_item_issues_copy.style.marginLeft = "auto";

        var button = list_item_issues_copy;
        button.id = "latest-button"
        button.href += "?sort=updated";
        button.style.float = "right";
```

**Comment by Ede123** [comment]
Thanks for looking into this!

Seems that right now GitLab switched back to using an unordered list again, but if you tested this before (I noticed the breakage as well) and it worked we can certainly add the patch, as it's compatible with the current list-based layout as well.

Do you want to create a PR?

**Comment by JourneyOver** [comment]
@Ede123 Yea looks like github ended up switching back to the list again instead of keeping the anchor elements, currently your current version of the script looks to be working again just fine because of this without having to mess with changing anything in the script. 

The above changes is compatible with the current list-based layout as well only because I had to add back the `.firstElementChild` to the button variable, while when it was the anchor elements it didn't work unless I removed the `.firstElementChild` from the button variable and I went ahead and switched the query selector to what they had switched it to while I was at it (as you'll notice in the edit dropdown from 2 days ago)

I can still go ahead and create a PR if you want, just let me know if you want me to!

**Comment by Ede123** [comment]
I'd be happy to merge the updated selector. It seems to be more future proof.

**Comment by JourneyOver** [comment]
Sorry I never got back to this, just got busy and kinda forgot all about this.. Seems like someone has made a PR though in the past month to fix the issue.

**Comment by jerone** [comment]
I know that GitHub changed their code to hook into for userscripts. I haven't looked into this situation, plus my time and interest in GitHub dropped to zero almost. Sorry I cannot help more.

**Comment by JourneyOver** [comment]
> I know that GitHub changed their code to hook into for userscripts. I haven't looked into this situation, plus my time and interest in GitHub dropped to zero almost. Sorry I cannot help more.

It's all good! Hopefully I can find a solution soon enough.

**Comment by JourneyOver** [comment]
Found what I believe is to be a fix thanks to https://github.com/refined-github/refined-github/issues/5719, seems I need to switch out `document.addEventListener('pjax:success', addLatestButton);` to be `document.addEventListener('turbo:render', addLatestButton);`. Will need to keep an eye on things but from my small little bit of testing so far before I go to work it seems to be working correctly again.

**Comment by jerone** [comment]
@JourneyOver Can you send an PR. Hopefully @Ede123 can merge it.
