### ISSUE TITLE
Twitter Show Hidden Content not working lately..

### ISSUE THREAD

**Issue by 7adm** [Ede123/userscripts#8]
Did twitter change something up? The script used to work flawlessly with violentmonkey couple of months ago. The posts are now being hidden by default again..

**Comment by Ede123** [comment]
I'm not using this script a lot, so I wouldn't notice any intermittent issues, but I just confirmed it still works for me.

Note that I did not update any of my userscripts for the Greasemonkey 4 API breakage, so (if Violentmonkey followed suit it's possible that this is what you're seeing.

If you find the cause of your issue and if it's something I can fix on my side feel free to re-open this bug.
